drop table IF EXISTS friendships, genres, likes, users, films, ratings, genres CASCADE;

CREATE TABLE IF NOT EXISTS ratings (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        rating VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(255) NOT NULL,
        login VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
        user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
        friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
        confirmation BOOLEAN
);

CREATE TABLE IF NOT EXISTS films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        description VARCHAR(255) NOT NULL,
        releaseDate DATE NOT NULL,
        duration INTEGER NOT NULL,
        rating INTEGER,
        FOREIGN KEY (rating) REFERENCES ratings (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        genre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS filmGenre (
        film_id  INTEGER,
        genre_id INTEGER,
        PRIMARY KEY (film_id, genre_id),
        FOREIGN KEY (film_Id) REFERENCES films (id) ON DELETE CASCADE,
        FOREIGN KEY (genre_Id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
       film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
       user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);