drop table IF EXISTS mpa, users, friendships, films, genres, filmGenre, likes CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(255) NOT NULL,
        login VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
        user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
        friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
        confirmation BOOLEAN
);

CREATE TABLE IF NOT EXISTS films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        description VARCHAR(255) NOT NULL,
        releaseDate DATE NOT NULL,
        duration INTEGER NOT NULL,
        mpa INTEGER,
        FOREIGN KEY (mpa) REFERENCES mpa (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS filmGenre (
        film_id  INTEGER,
        genre_id INTEGER,
        FOREIGN KEY (film_Id) REFERENCES films (id) ON DELETE CASCADE,
        FOREIGN KEY (genre_Id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
       film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
       user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);